apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  destination:
    namespace: spring-boot
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/ANANDHAKUMAR18/Spring-Boot-Application-CICD.git'
    targetRevision: HEAD
    path: ./java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
