apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${LABEL}
  template:
    metadata:
      labels:
        app: ${LABEL}
    spec:
      containers:
      - name: spring-boot-app
        image: ${DOCKER_USERNAME}/$DOCKER_IMAGE}:${DOCKER_TAG}
        ports:
        - containerPort: 8080
